### ISSUE TITLE
stable sort

### ISSUE THREAD

**Issue by umutacar** [MPLLang/mpllib#2]
Suggestion from @pcostanza 
Add a stable sort
When you use merge sort, you typically do so because you want a stable sort
In our merge sort, we use quicksort as our base case and this breaks stability

**Comment by shwestrick** [comment]
I believe our merge implementation might be unstable, too. We do a binary search to split the right side, but this doesn't ensure that the earliest such element is found.

This is an easy fix. But it might be nice to keep them separate, due to the difference in specification. So we could add StableMerge in addition to StableSort.

**Comment by shwestrick** [comment]
Started work in #3

**Comment by ghost** [comment]
I implemented a version of Cilk sort in Go some time ago, and it was a bit tricky to guarantee stability. Especially, it was necessary to have two different versions of binary search. Maybe you find the source code interesting: https://github.com/intel/forGoParallel/blob/main/psort/mergesort.go

**Comment by shwestrick** [comment]
Nice! Looking forward to reading though your implementation. I had a similar realization, of needing a stronger binary search (specifically I ended up needing to count the number of elements strictly less than the splitter, for merge).

**Comment by shwestrick** [comment]
Done; PR #3 merged. See https://github.com/MPLLang/mpllib/pull/3#issuecomment-1121274841 for summary.
